italia/design-angular-kit

src/app/shared/source-display/source-display.component.html
src/app/shared/source-display/source-display.component.ts

Corretto il bug del componente `source-display` che non permetteva di mostrarne più di uno nella stessa pagina. Inoltre è stato reso esplicito il linguaggio degli snippet di codice del componente.

Corretto il bug del componente di visualizzazione del codice

---

.circleci/config.yml

Introdotto lo step di minificazione nello script di CircleCI.

Step Minificazione CircleCi

---

projects/design-angular-kit/package.json

fix #53
Corretto refuso nelle peerDependecies del package.json della libreria.

fix: correggi refuso in peer dependencies

---

projects/design-angular-kit/package.json

fix #55
Aggiunta la dipendenza come peerDependencies della libreria `io-ts` alla libreria `design-angular-kit`

Fix: aggiungi io-ts come peerDependencies

---

.circleci/config.yml
github-pages.sh

Cambiato lo script di pubblicazione della documentazione su Github Pages in modo tale da non pubblicare nel caso in cui non ci siano state modifiche sul branch.

 chore: Pubblica la documentazione solamente se ci sono cambiamenti

---

src/app/tabs/tabs-index/tabs-index.component.html

Utilizza la componente it-api-parameters nella documentazione del componente Tab.
fix #85

aggiorna esempio del  componente Tab

---

README.md
package.json
projects/design-angular-kit/package.json
update-assets.sh

build: aggiunge README.md al pacchetto NPM

---

.github/workflows/publish-release.yml
.gitignore
.npmrc
.npmrc-dist
package-lock.json
package.json
scripts/wait-confirm.js

chore: release stuff

---

src/assets/scss/fonts.scss
src/styles.scss

chore: Corretta applicazione fonts nell'app di demo

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
src/app/app.component.html
src/app/welcome/welcome/welcome.component.html

 158-menu-laterale-non-funziona-su-mobile-rimane-sempre-aperto 

---

projects/design-angular-kit/src/lib/components/core/popover/popover.directive.spec.ts
projects/design-angular-kit/src/lib/components/core/tooltip/tooltip.directive.spec.ts
projects/design-angular-kit/src/lib/components/form/select/select.component.spec.ts
projects/design-angular-kit/src/lib/components/form/upload-file-list/upload-file-list.component.spec.ts

test :  fix tests for new components

---

projects/design-angular-kit/assets/i18n/it.json
projects/design-angular-kit/src/lib/components/core/chip/chip.component.html
projects/design-angular-kit/src/lib/components/core/chip/chip.component.spec.ts
projects/design-angular-kit/src/lib/components/core/chip/chip.component.ts
projects/design-angular-kit/src/lib/modules/components.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app-routing.module.ts
src/app/chip/chip-index/chip-index.component.html
src/app/chip/chip-index/chip-index.component.spec.ts
src/app/chip/chip-index/chip-index.component.ts
src/app/chip/chip-routing.module.ts
src/app/chip/chip.module.ts
src/app/chip/chips-colors/chips-colors.component.html
src/app/chip/chips-colors/chips-colors.component.spec.ts
src/app/chip/chips-colors/chips-colors.component.ts
src/app/chip/chips-disabled/chips-disabled.component.html
src/app/chip/chips-disabled/chips-disabled.component.spec.ts
src/app/chip/chips-disabled/chips-disabled.component.ts
src/app/chip/chips-example/chips-example.component.html
src/app/chip/chips-example/chips-example.component.spec.ts
src/app/chip/chips-example/chips-example.component.ts
src/app/chip/chips-examples/chips-examples.component.spec.ts
src/app/chip/chips-examples/chips-examples.component.tpl
src/app/chip/chips-examples/chips-examples.component.ts
src/app/chip/chips-group/chips-group.component.html
src/app/chip/chips-group/chips-group.component.spec.ts
src/app/chip/chips-group/chips-group.component.ts
src/assets/table-of-content.json

feat: add Chip component

---

projects/design-angular-kit/src/lib/components/core/forward/forward.directive.spec.ts
projects/design-angular-kit/src/lib/components/core/forward/forward.directive.ts
projects/design-angular-kit/src/lib/modules/components.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app-routing.module.ts
src/app/forward/forward-example/forward-example.component.html
src/app/forward/forward-example/forward-example.component.ts
src/app/forward/forward-examples/forward-examples.component.tpl
src/app/forward/forward-examples/forward-examples.component.ts
src/app/forward/forward-index/forward-index.component.html
src/app/forward/forward-index/forward-index.component.ts
src/app/forward/forward-routing.module.ts
src/app/forward/forward.module.ts
src/assets/table-of-content.json

feat: add forward directive

---

projects/design-angular-kit/src/lib/components/core/badge/badge.directive.spec.ts

Aggiunti test per 100% coverage della direttiva Badge

test: add test for badge directive

---

README.md
projects/design-angular-kit/assets/i18n/en.json
projects/design-angular-kit/assets/i18n/it.json
projects/design-angular-kit/src/lib/components/utils/language-switcher/language-switcher.component.html
projects/design-angular-kit/src/lib/components/utils/language-switcher/language-switcher.component.spec.ts
projects/design-angular-kit/src/lib/components/utils/language-switcher/language-switcher.component.ts
projects/design-angular-kit/src/lib/design-angular-kit.module.ts
projects/design-angular-kit/src/lib/interfaces/utils.ts
projects/design-angular-kit/src/lib/modules/components.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app.module.ts

- Fix #183: Adesso la localizzazione funziona in un progetto che non importa `TranslateModule.forRoot()` nell'`app.module.ts`
La modalità di estensione/personalizzazione delle label lato utente resta invariata (Aggiornato README.md)
- Aggiunta localizzazione inglese per la libreria
- Aggiunto `LanguageSwitcherComponent` (Dropdown che ti permette di cambiare lingua all'applicazione)

feat: Miglioramenti nella gestione della localizzazione (i18n)

---

projects/design-angular-kit/package.json
projects/design-angular-kit/src/lib/design-angular-kit.module.ts

#186 
Aggiunti @angular/animations e @angular/platform-browser come peerDependencies della libreria

chore(refactor): added BrowserAnimationsModule peerDependencies

---

projects/design-angular-kit/src/lib/components/form/input/input.component.ts
projects/design-angular-kit/src/lib/validators/it-validators.ts

fix: email input bad validation

---

projects/design-angular-kit/src/lib/components/form/upload-drag-drop/upload-drag-drop.component.ts
projects/design-angular-kit/src/lib/components/form/upload-file-list/upload-file-list.component.html
projects/design-angular-kit/src/lib/components/form/upload-file-list/upload-file-list.component.ts
projects/design-angular-kit/src/lib/interfaces/form.ts
src/app/app-routing.module.ts
src/app/upload/upload-drag-drop-example/upload-drag-drop-example.component.html
src/app/upload/upload-drag-drop-example/upload-drag-drop-example.component.spec.ts
src/app/upload/upload-drag-drop-example/upload-drag-drop-example.component.ts
src/app/upload/upload-examples/upload-examples.component.spec.ts
src/app/upload/upload-examples/upload-examples.component.tpl
src/app/upload/upload-examples/upload-examples.component.ts
src/app/upload/upload-file-list-example/upload-file-list-example.component.html
src/app/upload/upload-file-list-example/upload-file-list-example.component.spec.ts
src/app/upload/upload-file-list-example/upload-file-list-example.component.ts
src/app/upload/upload-image-list-example/upload-image-list-example.component.html
src/app/upload/upload-image-list-example/upload-image-list-example.component.spec.ts
src/app/upload/upload-image-list-example/upload-image-list-example.component.ts
src/app/upload/upload-index/upload-index.component.html
src/app/upload/upload-index/upload-index.component.spec.ts
src/app/upload/upload-index/upload-index.component.ts
src/app/upload/upload-routing.module.ts
src/app/upload/upload.module.ts
src/assets/table-of-content.json

- Verifica dell'issue #185 , la barra di progresso avanza correttamente. 
Il problema grafico è dovuto dal fatto che se il valore di progress viene aggiornato troppo velocemente, quindi arriva subito al 100%, non dà il tempo all'animazione di partire.
- Apportati dei fix minori a UploadDragDropComponent e UploadFileListComponent
- Aggiunta documentazione per UploadDragDropComponent e UploadFileListComponent

185 fix upload dragdrop component

---

projects/design-angular-kit/src/lib/components/navigation/back-button/back-button.component.html
projects/design-angular-kit/src/lib/components/navigation/back-button/back-button.component.scss
projects/design-angular-kit/src/lib/components/navigation/back-button/back-button.component.spec.ts
projects/design-angular-kit/src/lib/components/navigation/back-button/back-button.component.ts

- Fixes: #188 
- introdotta [soluzione](https://github.com/italia/design-angular-kit/pull/171#issuecomment-1374464577) discussa nel pr #171 
- Reintroduzione [test](https://github.com/italia/design-angular-kit/pull/171/commits/27dda67bca99126e82f05372694a484f989e5f02) implementato da @alenap93

fix: accessibilità e margini su back-button

---

projects/design-angular-kit/assets/i18n/en.json
projects/design-angular-kit/assets/i18n/it.json
projects/design-angular-kit/src/lib/components/core/steppers/steppers-container/steppers-container.component.html
projects/design-angular-kit/src/lib/components/core/steppers/steppers-container/steppers-container.component.spec.ts
projects/design-angular-kit/src/lib/components/core/steppers/steppers-container/steppers-container.component.ts
projects/design-angular-kit/src/lib/components/core/steppers/steppers-item/steppers-item.component.html
projects/design-angular-kit/src/lib/components/core/steppers/steppers-item/steppers-item.component.spec.ts
projects/design-angular-kit/src/lib/components/core/steppers/steppers-item/steppers-item.component.ts
projects/design-angular-kit/src/lib/components/core/tab/tab-container/tab-container.component.ts
projects/design-angular-kit/src/lib/components/core/tab/tab-item/tab-item.component.ts
projects/design-angular-kit/src/lib/interfaces/icon.ts
projects/design-angular-kit/src/lib/modules/components.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app-routing.module.ts
src/app/steppers/steppers-dynamic-example/steppers-dynamic-example.component.html
src/app/steppers/steppers-dynamic-example/steppers-dynamic-example.component.ts
src/app/steppers/steppers-examples/steppers-examples.component.tpl
src/app/steppers/steppers-examples/steppers-examples.component.ts
src/app/steppers/steppers-header-example/steppers-header-example.component.html
src/app/steppers/steppers-header-example/steppers-header-example.component.ts
src/app/steppers/steppers-index/steppers-index.component.html
src/app/steppers/steppers-index/steppers-index.component.ts
src/app/steppers/steppers-mobile-example/steppers-mobile-example.component.html
src/app/steppers/steppers-mobile-example/steppers-mobile-example.component.scss
src/app/steppers/steppers-mobile-example/steppers-mobile-example.component.ts
src/app/steppers/steppers-routing.module.ts
src/app/steppers/steppers.module.ts
src/assets/table-of-content.json

- Aggiunto Steppers Component: #200 
- Aggiunta icona `mastodon` introdotta in bootstrap-italia v2.3.0

feat: added steppers component

---

projects/design-angular-kit/src/lib/utils/regex.ts
src/app/form-input/model-driven-validation-example/model-driven-validation-example.component.html
src/app/form-input/model-driven-validation-example/model-driven-validation-example.component.ts

fix: italian tax-code regex

---

package-lock.json
projects/design-angular-kit/src/lib/components/core/notifications/notifications.component.html
projects/design-angular-kit/src/lib/components/core/notifications/notifications.component.ts
projects/design-angular-kit/src/lib/interfaces/core.ts
projects/design-angular-kit/src/lib/services/notifications/notifications.service.ts
src/app/app-routing.module.ts
src/app/notifications/notifications-example-type/notifications-example-type.component.html
src/app/notifications/notifications-example-type/notifications-example-type.component.spec.ts
src/app/notifications/notifications-example-type/notifications-example-type.component.ts
src/app/notifications/notifications-example/notifications-example.component.html
src/app/notifications/notifications-example/notifications-example.component.spec.ts
src/app/notifications/notifications-example/notifications-example.component.ts
src/app/notifications/notifications-examples/notifications-examples.component.spec.ts
src/app/notifications/notifications-examples/notifications-examples.component.tpl
src/app/notifications/notifications-examples/notifications-examples.component.ts
src/app/notifications/notifications-index/notifications-index.component.html
src/app/notifications/notifications-index/notifications-index.component.spec.ts
src/app/notifications/notifications-index/notifications-index.component.ts
src/app/notifications/notifications-routing.module.ts
src/app/notifications/notifications-setup/notifications-setup.component.html
src/app/notifications/notifications-setup/notifications-setup.component.spec.ts
src/app/notifications/notifications-setup/notifications-setup.component.ts
src/app/notifications/notifications.module.ts
src/app/shared/api-parameters/api-parameters.component.html
src/app/shared/api-parameters/api-parameters.component.ts
src/assets/table-of-content.json

#145 Aggiunta documentazione per il componente Notifications (it-notifications) 
- Ottimizzazione del componente Notifications (it-notifications) usando `ChangeDetectionStrategy.OnPush`
- Aggiunta possibilità di usare una icona custom per ogni notifica e fix [icona di default](https://italia.github.io/bootstrap-italia/docs/componenti/notifiche/#stati)
- Aggiunta una nuova pagina di documentazione dedicata al componente Notifications (it-notifications):
- Setup delle notifiche e configurazione globale
- Esempio di utilizzo standard (configurazione di defualt) con i diversi tipi di notifiche
- Esempio di utilizzo con configurazione su singola notifica
- Aggiunta possibilità di documentare i `Service`/`injectable` in `ApiParametersComponent` (documentazione)

chore(docs): added docs for the notifications component

---

projects/design-angular-kit/assets/i18n/en.json
projects/design-angular-kit/assets/i18n/it.json
projects/design-angular-kit/src/lib/components/core/rating/rating.component.html
projects/design-angular-kit/src/lib/components/core/rating/rating.component.spec.ts
projects/design-angular-kit/src/lib/components/core/rating/rating.component.ts
projects/design-angular-kit/src/lib/modules/components.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app-routing.module.ts
src/app/rating/rating-example-readonly/rating-example-readonly.component.html
src/app/rating/rating-example-readonly/rating-example-readonly.component.spec.ts
src/app/rating/rating-example-readonly/rating-example-readonly.component.ts
src/app/rating/rating-example/rating-example.component.html
src/app/rating/rating-example/rating-example.component.spec.ts
src/app/rating/rating-example/rating-example.component.ts
src/app/rating/rating-examples/rating-examples.component.spec.ts
src/app/rating/rating-examples/rating-examples.component.tpl
src/app/rating/rating-examples/rating-examples.component.ts
src/app/rating/rating-index/rating-index.component.html
src/app/rating/rating-index/rating-index.component.spec.ts
src/app/rating/rating-index/rating-index.component.ts
src/app/rating/rating-routing.module.ts
src/app/rating/rating.module.ts
src/assets/table-of-content.json

Realizzazione del componente rating #219

219 rating component

---

src/app/alert/alert-additional-content-example/alert-additional-content-example.component.html
src/app/alert/alert-additional-content-example/alert-additional-content-example.component.spec.ts
src/app/alert/alert-additional-content-example/alert-additional-content-example.component.ts
src/app/alert/alert-closing-example/alert-closing-example.component.html
src/app/alert/alert-closing-example/alert-closing-example.component.spec.ts
src/app/alert/alert-closing-example/alert-closing-example.component.ts
src/app/alert/alert-color-example/alert-color-example.component.html
src/app/alert/alert-color-example/alert-color-example.component.spec.ts
src/app/alert/alert-color-example/alert-color-example.component.ts
src/app/alert/alert-examples/alert-examples.component.spec.ts
src/app/alert/alert-examples/alert-examples.component.tpl
src/app/alert/alert-examples/alert-examples.component.ts
src/app/alert/alert-index/alert-index.component.html
src/app/alert/alert-index/alert-index.component.spec.ts
src/app/alert/alert-index/alert-index.component.ts
src/app/alert/alert-routing.module.ts
src/app/alert/alert.module.ts
src/app/app-routing.module.ts
src/assets/table-of-content.json

Aggiunta documentazione per il componente alert #136

Documentazione componente Alert

---

projects/design-angular-kit/src/lib/abstracts/abstract-form.component.ts
src/app/form-input/model-driven-validation-example/model-driven-validation-example.component.html
src/app/form-input/model-driven-validation-example/model-driven-validation-example.component.ts

fix: mark all as touched on form components

---

projects/design-angular-kit/src/lib/abstracts/abstract-form.component.ts
src/app/notifications/notifications-example-type/notifications-example-type.component.html
src/app/notifications/notifications-examples/notifications-examples.component.tpl
src/app/notifications/notifications-setup/notifications-setup.component.html
src/app/notifications/notifications-setup/notifications-setup.component.ts

#218 Migliorata documentazione: mi sono accorto che la parte di setup delle notifiche era poco chiara

docs: update notifications setup docs

---

projects/design-angular-kit/src/lib/components/utils/language-switcher/language-switcher.component.ts
src/app/app-routing.module.ts
src/app/language-switcher/language-switcher-custom-example/language-switcher-custom-example.component.html
src/app/language-switcher/language-switcher-custom-example/language-switcher-custom-example.component.spec.ts
src/app/language-switcher/language-switcher-custom-example/language-switcher-custom-example.component.ts
src/app/language-switcher/language-switcher-example/language-switcher-example.component.html
src/app/language-switcher/language-switcher-example/language-switcher-example.component.spec.ts
src/app/language-switcher/language-switcher-example/language-switcher-example.component.ts
src/app/language-switcher/language-switcher-examples/language-switcher-examples.component.spec.ts
src/app/language-switcher/language-switcher-examples/language-switcher-examples.component.tpl
src/app/language-switcher/language-switcher-examples/language-switcher-examples.component.ts
src/app/language-switcher/language-switcher-index/language-switcher-index.component.html
src/app/language-switcher/language-switcher-index/language-switcher-index.component.spec.ts
src/app/language-switcher/language-switcher-index/language-switcher-index.component.ts
src/app/language-switcher/language-switcher-routing.module.ts
src/app/language-switcher/language-switcher.module.ts
src/app/shared/shared.module.ts
src/assets/table-of-content.json

- Fix `LanguageSwitcherComponent`: non veniva recuperata correttamente la lingua corrente
- Aggiunta documentazione #214

Aggiunta documentazione per il componente Language Switcher

---

projects/design-angular-kit/src/lib/components/core/alert/alert.component.spec.ts

Realizzazione test per componente itAlert
Sono stati realizzati i test per il color primary e success

Test per componente itAlert

---

projects/design-angular-kit/src/lib/components/core/spinner/spinner.component.spec.ts

Realizzazione test per componente itSpinner
Sono stati realizzati i test per il active true/false e small true/false

test: add test for ItSpinner

---

projects/design-angular-kit/src/lib/components/form/input/input.component.html

Disabilitate le frecce nel caso in cui il campo input di tipo number sia disabilitato
fixes #275

fix: input number editable when disabled

---

package-lock.json
package.json
projects/design-angular-kit/package.json
projects/design-angular-kit/src/lib/components/form/input/input.component.html
projects/design-angular-kit/src/lib/components/form/input/input.component.scss
projects/design-angular-kit/src/lib/components/form/input/input.component.ts
src/app/form-input/form-input-example/form-input-example.component.html
src/app/form-input/form-input-number/form-input-number.component.html

fix: rework input fields

---

src/app/app-routing.module.ts
src/app/back-to-top/back-to-top-button/back-to-top-button.component.html
src/app/back-to-top/back-to-top-button/back-to-top-button.component.ts
src/app/back-to-top/back-to-top-examples/back-to-top-examples.component.spec.ts
src/app/back-to-top/back-to-top-examples/back-to-top-examples.component.tpl
src/app/back-to-top/back-to-top-examples/back-to-top-examples.component.ts
src/app/back-to-top/back-to-top-index/back-to-top-index.component.html
src/app/back-to-top/back-to-top-index/back-to-top-index.component.spec.ts
src/app/back-to-top/back-to-top-index/back-to-top-index.component.ts
src/app/back-to-top/back-to-top-routing.module.ts
src/app/back-to-top/back-to-top.module.ts
src/assets/table-of-content.json

docs: add back to top documentation

---

projects/design-angular-kit/src/lib/components/utils/icon/icon.component.html
projects/design-angular-kit/src/lib/components/utils/icon/icon.component.ts

fix: risolto il bug di accessibilità sul componente it-icon

---

projects/design-angular-kit/src/lib/utils/date-utils.ts

fix(DateUtils): fixed countDays function

---

projects/design-angular-kit/src/lib/components/core/popover/popover.directive.ts

- Fix dell'attributo container del componente popover #352 (@astagi controllerei anche la [documentazione ufficiale](https://italia.github.io/bootstrap-italia/docs/componenti/popover/#attivazione-con-opzione-container))

fix(popover): fixed popover container attribute

---

projects/design-angular-kit/src/lib/components/core/button/button.directive.ts

Aggiunto il tipo di default alla direttiva ItButton.
Closes: #355

fix(button): added default button type

---

.gitignore
CHANGELOG.md
package-lock.json
package.json
publiccode.yml
src/app/badge/badge-example/badge-example.component.html

Add a utils validation for plate with its regex and error label

Add validation for plate 

---

src/app/card/card-image/card-image.component.html
src/app/card/card-special/card-special.component.html
src/app/carousel/carousel-featured-image-example/carousel-featured-image-example.component.html
src/app/carousel/carousel-fullscreen-image-example/carousel-fullscreen-image-example.component.html
src/app/carousel/carousel-fullscreen-image-standard-example/carousel-fullscreen-image-standard-example.component.html
src/app/carousel/carousel-image-above-example/carousel-image-above-example.component.html
src/app/carousel/carousel-special-cards-example/carousel-special-cards-example.component.html
src/app/header/header-example/header-example.component.html
src/app/list/list-image/list-image.component.html
src/app/megamenu/megamenu-cta-bottom/megamenu-cta-bottom.component.html
src/app/megamenu/megamenu-cta-right/megamenu-cta-right.component.html
src/app/megamenu/megamenu-example/megamenu-example.component.html

docs: change placeholder service

---

package-lock.json
package.json
projects/design-angular-kit/src/lib/components/core/dimmer/dimmer.component.html
projects/design-angular-kit/src/lib/components/core/dimmer/dimmer.component.ts
src/app/badge/badge-example/badge-example.component.html
src/app/forward/forward-example/forward-example.component.html

chore: upgrade bsi

---

projects/design-angular-kit/src/lib/components/navigation/navscroll/navscroll.component.ts

Risolve il problema delle readonly segnalato in #400

fix: readonly input problem in Navscroll

---

projects/design-angular-kit/assets/i18n/en.json
projects/design-angular-kit/assets/i18n/it.json
projects/design-angular-kit/src/lib/components/form/transfer/transfer-list/transfer-list.component.html
projects/design-angular-kit/src/lib/components/form/transfer/transfer-list/transfer-list.component.ts
projects/design-angular-kit/src/lib/components/form/transfer/transfer.component.html
projects/design-angular-kit/src/lib/components/form/transfer/transfer.component.ts

fix: add translations to transfer

---

projects/design-angular-kit/src/lib/components/form/autocomplete/autocomplete.component.html

feat: add accessible autocomplete

---

projects/design-angular-kit/src/lib/components/form/transfer/transfer.component.ts
projects/design-angular-kit/src/lib/components/navigation/skiplink/skiplink-item/skiplink-item.component.ts
projects/design-angular-kit/src/lib/components/navigation/skiplink/skiplink/skiplink.component.ts

fix: components import

---

projects/design-angular-kit/src/lib/components/navigation/navscroll/navscroll.store.ts
src/app/app.component.html

fix: progress bar update on navscroll

---

package-lock.json
package.json
projects/design-angular-kit/src/lib/components/core/steppers/steppers-container/steppers-container.component.html
projects/design-angular-kit/src/lib/components/core/steppers/steppers-item/steppers-item.component.ts
projects/design-angular-kit/src/lib/components/core/tab/tab-container/tab-container.component.html
projects/design-angular-kit/src/lib/components/core/tab/tab-container/tab-container.component.ts
projects/design-angular-kit/src/lib/components/form/input/input.component.html
projects/design-angular-kit/src/lib/components/form/input/input.component.ts
projects/design-angular-kit/src/lib/components/form/textarea/textarea.component.scss
projects/design-angular-kit/src/lib/components/utils/icon/icon.component.html
projects/design-angular-kit/src/lib/components/utils/icon/icon.component.ts
src/app/icon/icon-example/icon-example.component.html
src/app/steppers/steppers-header-example/steppers-header-example.component.html
src/app/table-of-content-item/table-of-content-item.component.scss
src/app/table-of-content/table-of-content.component.scss
src/app/tabs/tabs-dynamic-example/tabs-dynamic-example.component.html
src/app/tabs/tabs-dynamic-example/tabs-dynamic-example.component.ts
src/app/tabs/tabs-example/tabs-example.component.html
src/app/tabs/tabs-example/tabs-example.component.ts

fix: upgrade to bsi 2.13.x

---

projects/design-angular-kit/src/lib/components/form/checkbox/checkbox.component.html
projects/design-angular-kit/src/lib/components/form/radio-button/radio-button.component.html
src/app/checkbox/checkbox-example-group/checkbox-example-group.component.html

fix: disabled checbox and radio rendering

---

projects/design-angular-kit/src/lib/abstracts/abstract-form.component.ts
src/app/form-input/form-input-example/form-input-example.component.html

fix: default validation

---

.devcontainer/devcontainer.json
.devcontainer/scripts/git/pre-push
.devcontainer/scripts/postCreateCommand.sh
projects/design-angular-kit/src/lib/components/core/video-player/video-player.component.ts

Added id to checkbox in videoplayer

fix: added id to checkbox in videoplayer

---

projects/design-angular-kit/src/lib/components/core/video-player/video-player.component.ts

This commit wraps the `videojs` player with a root zone invocation to prevent triggering change detection in Angular whenever an event occurs.
The `| async` pipe has also been removed to prevent it from being bundled into the initial bundle, as consumers may not use it at all. This is unnecessary now with signals, which function as a pure communication protocol to the view, similar to how a `BehaviorSubject` did previously.

fix: reduce change detection cycles in video player

---

projects/design-angular-kit/src/lib/design-angular-kit.module.ts

Come da titolo fixato l'import per risolvere questa issue https://github.com/italia/design-angular-kit/issues/462

fix: fixed import in module.ts

---

projects/design-angular-kit/src/lib/components/navigation/footer/footer.component.html
projects/design-angular-kit/src/lib/components/navigation/footer/footer.component.ts
projects/design-angular-kit/src/lib/design-angular-kit.module.ts
projects/design-angular-kit/src/public_api.ts
src/app/app-routing.module.ts
src/app/footer/footer-examples/footer-examples.component.tpl
src/app/footer/footer-examples/footer-examples.component.ts
src/app/footer/footer-index/footer-index.component.html
src/app/footer/footer-index/footer-index.component.ts
src/app/footer/footer-routing.module.ts
src/app/footer/footer-simple/footer-simple.component.html
src/app/footer/footer-simple/footer-simple.component.ts
src/app/footer/footer.module.ts
src/assets/table-of-content.json

feat: footer component
